variables:
- group: data-platform-kv
- group: databricks

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python38:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip setuptools wheel twine
    pip install -r requirements.txt
  displayName: 'Install dependencies'

  # - script: |
  #   python -m pip install flake8
  #   flake8 .
  # displayName: 'Run lint tests'

- script: |
    python setup.py sdist bdist_wheel
    ls dist/
  displayName: 'Artifact creation'

- script: |
    export SKIP_INTEGRATION=True

    export AUTH_TYPE=USER
    export DBUTILSTOKEN=dapixxx
    export TENANT_ID=11111111-0000-0000-0000-000000000000
    export SP_CLIENT_ID=22222222-0000-0000-0000-000000000000
    export SP_CLIENT_SECRET=ThisIsTheSecret
    export AD_RESOURCE=33333333-0000-0000-0000-000000000000
    export MGMT_RESOURCE_ENDPOINT=https://management.core.windows.net/
    export WORKSPACE_NAME=workspacename
    export RESOURCE_GROUP=resourcegroup
    export SUBSCRIPTION_ID=44444444-0000-0000-0000-000000000000
    export DATABRICKS_API_HOST=https://wwww.autobricks.net
    
    pip install .
    pytest test/unit --junitxml=junit/test-results.xml --cov=autobricks --cov-report=xml --cov-report=html
  displayName: 'Unit Tests'


- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Publish test results for Python $(python.version)'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      dist/**
      deployment/**
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Build Artefacts'

- task: TwineAuthenticate@0
  inputs:
    # artifactFeeds: 'sibytes'
    externalFeeds: 'pypi'
  displayName: 'Authenticate Twine'

- script: |
    twine upload -r pypi --config-file $(PYPIRC_PATH) $(Build.SourcesDirectory)/dist/*
  continueOnError: true
  displayName: 'Publish to Artefact Store'
