{
    "name": "dbx-pattern: autoloader-raw-schema-test",
    "email_notifications": {
        "on_start": [
            "shaun_chiburi@hotmail.com"
        ],
        "on_success": [
            "shaun_chiburi@hotmail.com"
        ],
        "on_failure": [
            "shaun_chiburi@hotmail.com"
        ],
        "no_alert_for_skipped_runs": false
    },
    "webhook_notifications": {},
    "notification_settings": {
        "no_alert_for_skipped_runs": false,
        "no_alert_for_canceled_runs": false
    },
    "timeout_seconds": 0,
    "max_concurrent_runs": 1,
    "tasks": [
        {
            "task_key": "load_raw_customers",
            "notebook_task": {
                "notebook_path": "/Repos/shaun.ryan@shaunchiburihotmail.onmicrosoft.com/databricks-patterns/Databricks/Notebooks/Bronze/autoload_raw_schema",
                "base_parameters": {
                    "table": "customers",
                    "process_id": "{{job_id}}"
                },
                "source": "WORKSPACE"
            },
            "existing_cluster_id": "0407-084948-1ov2zao",
            "timeout_seconds": 0,
            "email_notifications": {},
            "notification_settings": {
                "no_alert_for_skipped_runs": false,
                "no_alert_for_canceled_runs": false,
                "alert_on_last_attempt": false
            }
        }
    ],
    "format": "MULTI_TASK"
}
